# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxGghFBOm_VyEZyIxW13jkRk1IwcOx8Q
"""

import os, re, csv, math
import numpy as np
from collections import Counter, defaultdict

# ---------- Preprocessing ----------
def preprocess(text):
    return re.findall(r'\w+', text.lower())

# ---------- Loading ----------
def load_txt(path):
    docs = []
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            line = line.strip()
            if line != '':
                docs.append(line)
    return docs

def load_csv(path, column):
    docs = []
    with open(path, 'r', encoding='utf-8') as f:
        rdr = csv.DictReader(f)
        for row in rdr:
            text = (row.get(column) or '').strip()
            if text:
                docs.append(text)
    return docs

def load_and_preprocess_docs(file_paths):
    docs = []
    for path in file_paths:
        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
            text = f.read().strip()
            if text:
                docs.append(text)   # ⬅️ no preprocess here
    return docs

# ---------- Inverted Index ----------
def build_inverted_index(docs):
    index = {}
    for doc_id, text in enumerate(docs):
        for term in set(preprocess(text)):
            index.setdefault(term, []).append(doc_id)
    return {t: sorted(set(ids)) for t, ids in index.items()}

def get_postings(inv, term):
    return set(inv.get(term.lower(), []))

def boolean_and(inv, t1, t2):
    return sorted(get_postings(inv, t1) & get_postings(inv, t2))

def boolean_or(inv, t1, t2):
    return sorted(get_postings(inv, t1) | get_postings(inv, t2))

def boolean_not(inv, t, N):
    return sorted(set(range(N)) - get_postings(inv, t))

def eval_query(query, inv, N):
    tokens = query.lower().split()
    result = set(range(N))
    i = 0
    while i < len(tokens):
        token = tokens[i]
        if token == "and":
            i += 1
            result &= get_postings(inv, tokens[i])
        elif token == "or":
            i += 1
            result |= get_postings(inv, tokens[i])
        elif token == "not":
            i += 1
            result -= get_postings(inv, tokens[i])
        else:
            result &= get_postings(inv, token)
        i += 1
    return sorted(result)

# ---------- Vector Space Model ----------
def build_tfidf(docs):
    tokens = [preprocess(d) for d in docs]
    N = len(docs)
    unique_tokens = sorted(set(t for d in tokens for t in d))
    vocab = {t: i for i, t in enumerate(unique_tokens)}
    V = len(vocab)
    tf = np.zeros((V, N))
    for j, d in enumerate(tokens):
        for t, c in Counter(d).items():
            tf[vocab[t], j] = c
    df = np.count_nonzero(tf > 0, axis=1)
    idf = np.log((N + 1) / (df + 1)) + 1
    tfidf = (tf.T * idf).T
    return vocab, tf, tfidf, idf

def vectorize_query(query, vocab, idf):
    q = np.zeros(len(vocab))
    for t, c in Counter(preprocess(query)).items():
        if t in vocab:
            q[vocab[t]] = c
    return q * idf

def cosine_sim(q, D):
    return (q @ D) / (np.linalg.norm(q) + 1e-12) / (np.linalg.norm(D, axis=0) + 1e-12)

def jaccard_sim(q, D):
    qb = (q > 0).astype(int)[:, None]
    Db = (D > 0).astype(int)
    inter = (qb * Db).sum(axis=0)
    union = (qb + Db - (qb * Db)).sum(axis=0) + 1e-12
    return inter / union

def dice_sim(q, D):
    qb = (q > 0).astype(int)[:, None]
    Db = (D > 0).astype(int)
    inter = (qb * Db).sum(axis=0)
    denom = qb.sum() + Db.sum(axis=0) + 1e-12
    return 2 * inter / denom

# ---------- BIM (Condensed Version) ----------
def bim_search(vocab, docs, query, relevance=None):
    N = len(docs)
    pd = {i: preprocess(docs[i]) for i in range(N)}
    df = defaultdict(int)
    for tokens in pd.values():
        for t in set(tokens):
            df[t] += 1
    qt = preprocess(query)

    def phase1(): return {t: math.log((N-dk+0.5)/(dk+0.5)) for t, dk in df.items()}

    def phase2():
        if not relevance:
            return phase1()
        Nr = len(relevance)
        rk = defaultdict(int)
        for i in relevance:
            for t in set(pd[i]):
                rk[t] += 1
        w = {}
        for t, dk in df.items():
            r = rk.get(t,0)
            w[t] = math.log(((r+0.5)/(Nr-r+0.5))/((dk-r+0.5)/(N-dk-Nr+r+0.5)))
        return w

    def score(weights):
        s = {}
        for i, tokens in pd.items():
            s[i] = sum(weights[t] for t in qt if t in tokens and t in weights)
        return sorted(s.items(), key=lambda x:x[1], reverse=True)

    w1 = phase1()
    r1 = score(w1)
    r2 = score(phase2()) if relevance else r1
    return r1, r2

# ---------- Example ----------
if __name__ == "__main__":
    document_paths = ['/content/d1.txt', "/content/d2.txt", "/content/d3.txt"]
    docs = load_and_preprocess_docs(document_paths)
    print(docs)

    inv = build_inverted_index(docs)
    N = len(docs)
    print("AND:", boolean_and(inv, "cats", "dogs"))
    print("OR :", boolean_or(inv, "cats", "dogs"))
    print("NOT:", boolean_not(inv, "birds", len(docs)))
    q1 = "cats AND dogs NOT birds"
    print(q1, "->", eval_query(q1, inv, N))

    vocab, tf, tfidf, idf = build_tfidf(docs)
    qvec = vectorize_query("cats dogs", vocab, idf)
    print("Cosine :", cosine_sim(qvec, tfidf))
    print("Jaccard:", jaccard_sim(qvec, tfidf))
    print("Dice   :", dice_sim(qvec, tfidf))

    ranked_phase1, ranked_phase2 = bim_search(vocab, docs, "cats dogs", relevance=[0])
    print("BIM Phase 1:", ranked_phase1)
    print("BIM Phase 2:", ranked_phase2)

